---
- name: Install baseline packages
  loop: "{{ packages[ansible_pkg_mgr] | union(packages['default']) }}"
  ansible.builtin.package:
    name: "{{ item }}"
    state: latest

- name: Ensure default shell is /bin/zsh for "{{ ansible_user_id }}"
  ansible.builtin.user:
    name: "{{ ansible_user_id }}"
    shell: /bin/zsh
