---
- name: Install baseline packages
  package:
    name: "{{ item }}"
    state: latest
  loop: "{{ packages[ansible_pkg_mgr] | default(packages['default']) }}"

- name: Ensure default shell is /bin/zsh for "{{ ansible_user }}"
  ansible.builtin.user:
    name: "{{ ansible_user }}"
    shell: /bin/zsh
