---
- name: Install baseline packages
  package:
    name: "{{ item }}"
    state: latest
  loop: "{{ packages[ansible_pkg_mgr] | zip(packages['default']) | list }}"

- name: Ensure default shell is /bin/zsh for "{{ ansible_user_id }}"
  ansible.builtin.user:
    name: "{{ ansible_user_id }}"
    shell: /bin/zsh
