---
- name: Install VSCodium on Fedora
  become: true
  when: ansible_pkg_mgr == "dnf"
  block:
    - name: Import VSCodium GPG key
      ansible.builtin.rpm_key:
        key: https://gitlab.com/paulcarroty/vscodium-deb-rpm-repo/-/raw/master/pub.gpg
        state: present
    - name: Add VSCodium repository
      ansible.builtin.yum_repository:
        name: vscodium
        description: VSCodium
        baseurl: https://download.vscodium.com/rpms/
        gpgkey: https://gitlab.com/paulcarroty/vscodium-deb-rpm-repo/-/raw/master/pub.gpg
        gpgcheck: true
        state: present
    - name: Install VSCodium
      ansible.builtin.dnf:
        name: codium
        state: latest

- name: Install VSCodium on macOS
  when: ansible_pkg_mgr == "homebrew"
  community.general.homebrew:
    name: vscodium
    state: latest
