---
- name: Install Starship on Linux
  become: true
  when: ansible_pkg_mgr != "homebrew"
  block:
    - community.general.copr:
        name: atim/starship
        state: enabled
    - ansible.builtin.dnf:
        name: starship
        state: latest

- name: Install Starship on macOS
  when: ansible_pkg_mgr == "homebrew"
  community.general.homebrew:
    name: starship
    state: latest

- name: Add Starship to Zsh
  ansible.builtin.lineinfile:
    path: "{{ ansible_env.HOME }}/.zshrc"
    line: 'eval "$(starship init zsh)"'
    create: true
