---
- name: Install Starship on Linux
  when: ansible_pkg_mgr != "brew"
  shell: "curl -sS https://starship.rs/install.sh | sh"
  args:
    creates: "{{ ansible_env.HOME }}/bin/starship"
  register: starship_install

- name: Install Starship on macOS
  when: ansible_pkg_mgr == "brew"
  community.general.homebrew:
    name: starship
    state: latest

- name: Add Starship to Zsh
  lineinfile:
    path: "{{ ansible_env.HOME }}/.zshrc"
    line: 'eval "$(starship init zsh)"'
    create: true
  when: starship_install.changed
