---
- name: Install JetBrains Mono Nerd Font on Linux
  when: ansible_pkg_mgr != "brew"
  block:
    - name: Check if ~/.fonts exists
      file:
        path: "{{ lookup('env', 'HOME') }}/.fonts"
        state: directory

    - name: Check if JetBrains Mono Nerd Font is installed
      stat:
        path: "{{ lookup('env', 'HOME') }}/.fonts/JetBrainsMonoNerdFont-Regular.ttf"
      register: font_exists

    - name: Download JetBrains Mono Nerd Font
      when: font_exists.stat.exists is not true
      ansible.builtin.unarchive:
        src: https://github.com/ryanoasis/nerd-fonts/releases/latest/download/JetBrainsMono.tar.xz
        dest: "{{ lookup('env', 'HOME') }}/.fonts/"
        remote_src: true

- name: Install JetBrains Mono Nerd Font on macOS
  when: ansible_pkg_mgr == "brew"
  community.general.homebrew:
    name: font-jetbrains-mono-nerd-font
    state: latest
